#!/bin/bash

# Read current blocks file.
blocks_file=~/.user/.blocks
[ ! -f "$blocks_file" ] && echo "[bar.sh] Creating: $blocks_file" && touch $blocks_file

# Date.
status_date () {
	echo -n "$(date '+^b#81a2be^ [ %b %d]') "
}

# Clock.
status_clock () {
	echo -n "$(date '+^b#b294bb^ [ %H:%M]') "
}

# CPU Average Load.
status_cpu () {
	echo -n "^b#f0c674^ [ $(cut -d " " -f 1 /proc/loadavg)] "
}

# RAM Usage.
status_ram () {
	free -m | awk 'NR==2{printf "^b#8abeb7^ [ %sM] ", $3}'
}

# Volume. [dep: pulseaudio-utils]
status_volume () {
	awk -F" / " '/front-left: / { printf "^b#b5bd68^ [ %s] ", $2 }' <(pactl get-sink-volume @DEFAULT_SINK@)	
}

# Keyboard Layout.
status_xkb() {
	echo -n "^b#f0c674^ [ $(setxkbmap -query | awk -F"(,|[ ]+)" '/layout: / { print $2 }')] "
}

# Status loop.
while true
do
	# Append blocks.
	blocks=$(cat "$blocks_file")
	status=""
	grep -q "date" <<< "$blocks" && status=$status$(status_date)
	grep -q "clock" <<< "$blocks" && status=$status$(status_clock)
	grep -q "cpu" <<< "$blocks" && status=$status$(status_cpu)
	grep -q "ram" <<< "$blocks" && status=$status$(status_ram)
	grep -q "volume" <<< "$blocks" && status=$status$(status_volume)
	grep -q "xkb" <<< "$blocks" && status=$status$(status_xkb)

	# Set status bar.
	xsetroot -name "^c#373b41^$status"
	sleep .5
done
